/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-8.1
 * 
 * Declare the raycasterfs string.
 *
 */
#ifndef raycasterfs_h
#define raycasterfs_h

#include "vtkRenderingVolumeOpenGL2Module.h"

VTKRENDERINGVOLUMEOPENGL2_EXPORT extern const char *raycasterfs;

#endif /* #ifndef raycasterfs_h */
