/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-8.1
 * 
 * Declare the vtkFXAAFilterFS string.
 *
 */
#ifndef vtkFXAAFilterFS_h
#define vtkFXAAFilterFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkFXAAFilterFS;

#endif /* #ifndef vtkFXAAFilterFS_h */
