/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-8.1
 * 
 * Declare the vtkglProjectedTetrahedraFS string.
 *
 */
#ifndef vtkglProjectedTetrahedraFS_h
#define vtkglProjectedTetrahedraFS_h

#include "vtkRenderingVolumeOpenGL2Module.h"

VTKRENDERINGVOLUMEOPENGL2_EXPORT extern const char *vtkglProjectedTetrahedraFS;

#endif /* #ifndef vtkglProjectedTetrahedraFS_h */
