/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-8.1
 * 
 * Declare the vtkPolyDataFS string.
 *
 */
#ifndef vtkPolyDataFS_h
#define vtkPolyDataFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkPolyDataFS;

#endif /* #ifndef vtkPolyDataFS_h */
