/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-8.1
 * 
 * Declare the vtkPointGaussianVS string.
 *
 */
#ifndef vtkPointGaussianVS_h
#define vtkPointGaussianVS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkPointGaussianVS;

#endif /* #ifndef vtkPointGaussianVS_h */
